airplaneWorkshop/config/routes.rb
Rails.application.routes.draw do

  resources :planes
  resources :airplanes
    resources :sessions, only: [:new, :create, :destroy]
    
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    
    resources :users
    
    get 'home/index'
    root 'home#index'
end

airplaneWorkshop/app/models/airplane.rb
class Airplane < ApplicationRecord
end

airplaneWorkshop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

airplaneWorkshop/app/models/plane.rb
class Plane < ApplicationRecord
end

airplaneWorkshop/app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    validates :first_name,
        presence: true;
    validates :email,
        presence: true,
        uniqueness: true,
        format: {
            with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
    
    def to_s
        "#{first_name} #{email}"
    end
end

airplaneWorkshop/app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:brand, :model, :fault)
    end
end

airplaneWorkshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
    
    private
    def current_user
        User.where(id: session[:user_id]).first
    end
    
    helper_method :current_user
    
    private
    def login_required
        unless current_user
            flash[:alert] = "You must first log in or register before accessing this page!"
            redirect_to login_url
        end
    end
end

airplaneWorkshop/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

airplaneWorkshop/app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_filter :login_required    
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    #@planes = Plane.all
      @planes = Plane.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:brand, :model, :fault)
    end
end

airplaneWorkshop/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to root_url, notice: 'Logged in!'
        else
            render :new
        end
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_url, notice: 'Logged out'
  end
end

airplaneWorkshop/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
          session[:user_id] = @user.id
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :email, :password, :password_confirmation)
    end
end

airplaneWorkshop/app/helpers/airplanes_helper.rb
module AirplanesHelper
end

airplaneWorkshop/app/helpers/application_helper.rb
module ApplicationHelper
end

airplaneWorkshop/app/helpers/home_helper.rb
module HomeHelper
end

airplaneWorkshop/app/helpers/planes_helper.rb
module PlanesHelper
end

airplaneWorkshop/app/helpers/sessions_helper.rb
module SessionsHelper
end

airplaneWorkshop/app/helpers/users_helper.rb
module UsersHelper
end

airplaneWorkshop/app/views/airplanes/_form.html.erb
<%= form_for(airplane) do |f| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :fault %>
    <%= f.text_area :fault %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

airplaneWorkshop/app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

airplaneWorkshop/app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Fault</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.brand %></td>
        <td><%= airplane.model %></td>
        <td><%= airplane.fault %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

airplaneWorkshop/app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Back', airplanes_path %>

airplaneWorkshop/app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @airplane.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @airplane.model %>
</p>

<p>
  <strong>Fault:</strong>
  <%= @airplane.fault %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>

airplaneWorkshop/app/views/home/index.html.erb
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="col-lg-6 col-lg-push-3 col-md-8 col-md-push-2 col-sm-12">
            <div class="panel panel-default">
              <div class="panel-heading text-center">
                  Airplanes Workshop Application
              </div>
              <div class="panel-body">
                This is my Ruby on Rails app wrote to pass first project of Websites Architecture classes on the University of Gdańsk
              </div>
              <div class="panel-footer text-center">
                2016 Ⓡ Marcin Hallman ~ github/Strugacki 
              </div>
            </div>
        </div>
    </div>
</div>

airplaneWorkshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirplaneWorkshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

   <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Airplanes Workshop</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/planes/">Planes</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
     <% if current_user %>
        <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Log out <%= current_user.email %></a></li>
     <% else %>
        <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
        <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
     <% end %>
    </ul>
  </div>
</nav>
    
    <% flash.each do |key, value| %>
        <%= content_tag(:div, class: "alert alert-#{key}") do %>
            <p><%= value %></p>
        <% end %>
    <% end %>
<%= yield %>

</body>
</html>

airplaneWorkshop/app/views/planes/_form.html.erb
<%= form_for @plane, :html => {:class => "form-horizontal center"} do |f| %>
      <% if plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     <div class="row">
         <div class="form-group">
          <%= f.label :brand, "Brand:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
        <div class="col-lg-8 col-md-8 col-sm-10">
          <%= f.text_field :brand, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
          <%= f.label :model, "Model:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
        <div class="col-lg-8 col-md-8 col-sm-10">
            <%= f.text_field :model, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fault, "Fault:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
        <div class="col-lg-8 col-md-8 col-sm-10">
                    <%= f.text_area :fault, class: "form-control" %>
        </div>
      </div>
      <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
            </div>  
        </div>
     </div>  
 <% end %>

airplaneWorkshop/app/views/planes/edit.html.erb
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <h1>Editing Plane</h1>
    </div>  
</div>
<%= render 'form', plane: @plane %>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <%= link_to 'Show', @plane %> |
        <%= link_to 'Back', planes_path %>
    </div>  
</div>

airplaneWorkshop/app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <h1>Planes</h1>
    </div>  
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <a class="btn btn-primary btn-sm" href="/planes/new">New plane</a>
    </div>  
</div>
<div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Brand</th>
          <th>Model</th>
          <th>Fault</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @planes.each do |plane| %>
          <tr>
            <td><%= plane.brand %></td>
            <td><%= plane.model %></td>
            <td><%= plane.fault %></td>
            <td><%= link_to 'Show', plane %></td>
            <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
            <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <%= will_paginate @planes %>
    </div>  
</div>
<br>

airplaneWorkshop/app/views/planes/new.html.erb
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <h1>New Plane</h1>
    </div>  
</div>

<%= render 'form', plane: @plane %>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <%= link_to 'Back', planes_path %>
    </div>  
</div>

airplaneWorkshop/app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
    <div class="col-lg-6 col-lg-push-3 col-md-8 col-md-push-2 col-sm-12">
        <div class="panel panel-info">
          <div class="panel-heading">Brand/Model: <%= @plane.brand %> <%= @plane.model %></div>
          <div class="panel-body"><%= @plane.fault %></div>
          <div class="panel-footer text-center">
                  <%= link_to 'Edit', edit_plane_path(@plane) %> |
                <%= link_to 'Back', planes_path %>
          </div>
        </div>
    </div>
</div>

airplaneWorkshop/app/views/users/_form.html.erb
<%= form_for @user , :html => {:class => "form-horizontal center"} do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

     <div class="row">
         <div class="form-group">
             <%= f.label :first_name, "First name:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
            <div class="col-lg-8 col-md-8 col-sm-10">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :email, "Email:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
            <div class="col-lg-8 col-md-8 col-sm-10">
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :password, "Password:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
            <div class="col-lg-8 col-md-8 col-sm-10">
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
              <%= f.label :password_confirmation, "Password confirmation:", class: "col-lg-2 col-md-2 col-sm-1 control-label" %>
            <div class="col-lg-8 col-md-8 col-sm-10">
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>
          <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                    <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
                </div>  
            </div>
    </div>
<% end %>

airplaneWorkshop/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

airplaneWorkshop/app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

airplaneWorkshop/app/views/users/new.html.erb
<div class="row">
    <div class="col-lg-6 col-lg-push-3 col-md-8 col-md-push-2 col-sm-12 text-center">
        <h1>Registration form</h1>
    </div>
</div>
<%= render 'form', user: @user %>

airplaneWorkshop/app/views/users/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>